variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - maven_build
  - docker_release

maven-build:
  image: maven:3-jdk-8
  stage: maven_build
  script: "mvn package -B -DskipTests"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  stage: docker_release
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master